
name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # schedule:
  #    - cron: "0 0 * * *"

jobs:

  build-go:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Add tidy comment 
      run: go mod tidy 

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - run: mkdir -p dist
    - run: echo hello > dist/ar.txt

    
    - name: upload artifact 
      uses: actions/upload-artifact@v4
      with:
        name: Build artifact
        path: dist
       

    
    - name: Deploy to vm via ssh 
      uses: appleboy/ssh-action@v1
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USERNAME }}
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       port: 22
       script: |
        export PATH="$HOME/go/bin:/usr/local/go/bin:$PATH"
        cd ~/go/src/user_managment
        git pull origin master
        go mod tidy
        cd cmd/api || exit 1
        go build -o myapp main.go
        sudo systemctl daemon-reload
        sudo systemctl restart user.service

  download-artifact:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v5
        with:
          name: Build artifact
          path: artifact
      - name: display structure of artifact file 
        run: ls -R artifact
